### ISSUE TITLE
Routes can be overridden?

### ISSUE THREAD

**Issue by erik5388** [FlexSearch/FlexSearch#19]
Unless I'm missing something... 

A **GET** request to the following API route

> http://localhost/indices

Should return a list of known/created indices.

However I get the following error:

```json
{  
   "DeveloperMessage":"The requested index does not exist.",
   "UserMessage":"The requested index does not exist.",
   "ErrorCode":1000
}
```

Which is fine... but I'm not looking for a single index. I'm looking to run a "get all" as the documentation suggests (http://www.flexsearch.net/docs/rest/index-management-apis/#get-all-index).

By mistake though... I found that I could create an index called "indices" by posting the following:

```json
{  
   "indexName":"test"
}
```

To the following url: 

> http://localhost/indices

Guess what happens? It created an index named "indices" and not "test". 

Suggestions here?

**Comment by erik5388** [comment]
-v FlexSearch 0.21.1.0

**Comment by seemantr** [comment]
@erik Thanks for raising this issue. Actually mentioning the FlexSearch version was really helpful. Both of your issues are fixed in the latest release 0.23.2. I just uploaded it to the release section. We are working on releasing beta version in a month's time and haven't really updated our release packages on Github. There will be some changes between this and the beta but nothing major.

**Comment by erik5388** [comment]
Awesome. I'd love to continue help testing. I'll update and see if I can't find anything for you.

**Comment by seemantr** [comment]
Thanks @erik5388 , Feel free to get in touch regarding anything else. I would be very happy to take on board any suggestions that you may have about the product. In case you are interested in a .net port of Lucene then have a look at https://github.com/FlexSearch/FlexLucene . It is an automatically converted port where we have put in a lot of effort to make it more .net style by overriding method names etc.

**Comment by erik5388** [comment]
@seemantr FlexSearch is not using FlexLucene underneath? Or is it?

**Comment by seemantr** [comment]
@erik5388 Yes FlexSearch is using FlexLucene underneath. Rather than adding a lot of functionality to FlexSearch we have concentrated on adding it to FlexLucene so that non FlexSearch users can make use of it. Most of the changes we have done in last few months are in  0.24 branch. We are working towards our candidate release as most of the features are nealy complete.
